application: kellen-green 
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^.+
- ^README\.md

handlers:

# static files
- url: /static/
  static_dir: static
  
# everything else
- url: /
  static_files: index.html
  upload: index\.html