runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^README\.md

handlers:

# static files
- url: /static/
  static_dir: static
  
# root
- url: /
  static_files: index.html
  upload: index\.html
