application: kellen-green 
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- \.git
- \.idea
- google_appengine

handlers:

#static files
- url: /static
  static_dir: static
  
#favicon
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

#everything else
- url: /
  static_files: index.html
  upload: index\.html